dudek_user:
    resource: "@DudekUserBundle/Resources/config/routing.yml"
    prefix:   /

dudek_form:
    resource: "@DudekFormBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
