services:
    dudek.ldap_manager:
        class: Dudek\FormBundle\Services\LdapManager
        arguments: [ "%ldap_user%", "%ldap_password%"]

    dudek.user_listener:
        class: Dudek\FormBundle\EventListener\UserListener
        tags:
            - { name: kernel.event_subscriber }
