parameters:
#    dudek_form.example.class: Dudek\FormBundle\Example

services:
#    dudek_form.example:
#        class: %dudek_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
